Remove Ubuntu 24.10 "Oracular" that no longer builds
Oracular was supported only until July 2025:

https://discourse.ubuntu.com/t/oracular-oriole-release-notes/44878#p-112442-support-lifespan

It was apparently archived now and the Oracular images fail to build:

    + apt-get update
    Ign:1 http://archive.ubuntu.com/ubuntu oracular InRelease
    Ign:2 http://security.ubuntu.com/ubuntu oracular-security InRelease
    Ign:3 http://archive.ubuntu.com/ubuntu oracular-updates InRelease
    Ign:4 http://archive.ubuntu.com/ubuntu oracular-backports InRelease
    Err:5 http://security.ubuntu.com/ubuntu oracular-security Release
      404  Not Found [IP: 185.125.190.83 80]
    Err:6 http://archive.ubuntu.com/ubuntu oracular Release
      404  Not Found [IP: 91.189.91.81 80]
    Err:7 http://archive.ubuntu.com/ubuntu oracular-updates Release
      404  Not Found [IP: 91.189.91.81 80]
    Err:8 http://archive.ubuntu.com/ubuntu oracular-backports Release
      404  Not Found [IP: 91.189.91.81 80]
    Reading package lists...
    E: The repository 'http://security.ubuntu.com/ubuntu oracular-security Release' does not have a Release file.
    E: The repository 'http://archive.ubuntu.com/ubuntu oracular Release' does not have a Release file.
    E: The repository 'http://archive.ubuntu.com/ubuntu oracular-updates Release' does not have a Release file.
    E: The repository 'http://archive.ubuntu.com/ubuntu oracular-backports Release' does not have a Release file.
    Error: building at STEP "RUN /initialize $VENDOR $RELEASE && rm -f /initialize": while running runtime: exit status 100