ccache: print more detailed reasons why the compiler commands were uncacheable
Example:
```
+ ccache -svv
Cache directory:                          /home/runner/.ccache
Config file:                              /home/runner/.ccache/ccache.conf
System config file:                       /etc/ccache.conf
Stats updated:                            Sat Jan 25 13:34:26 2025
Stats zeroed:                             Sat Jan 25 13:32:38 2025
Cacheable calls:                           314 / 628 (50.00%)
  Hits:                                    301 / 314 (95.86%)
    Direct:                                  0 / 301 ( 0.00%)
    Preprocessed:                          301 / 301 (100.0%)
  Misses:                                   13 / 314 ( 4.14%)
Uncacheable calls:                         314 / 628 (50.00%)
  Autoconf compile/link:                     0 / 314 ( 0.00%)
  Bad compiler arguments:                    0 / 314 ( 0.00%)
  Called for linking:                      314 / 314 (100.0%)
  Called for preprocessing:                  0 / 314 ( 0.00%)
  Ccache disabled:                           0 / 314 ( 0.00%)
  Compilation failed:                        0 / 314 ( 0.00%)
  Compiler output file missing:              0 / 314 ( 0.00%)
  Compiler produced empty output:            0 / 314 ( 0.00%)
  Compiler produced stdout:                  0 / 314 ( 0.00%)
  Could not use modules:                     0 / 314 ( 0.00%)
  Could not use precompiled header:          0 / 314 ( 0.00%)
  Forced recache:                            0 / 314 ( 0.00%)
  Multiple source files:                     0 / 314 ( 0.00%)
  No input file:                             0 / 314 ( 0.00%)
  Output to stdout:                          0 / 314 ( 0.00%)
  Preprocessing failed:                      0 / 314 ( 0.00%)
  Unsupported code directive:                0 / 314 ( 0.00%)
  Unsupported compiler option:               0 / 314 ( 0.00%)
  Unsupported environment variable:          0 / 314 ( 0.00%)
  Unsupported source language:               0 / 314 ( 0.00%)
Errors:                                      0 / 628 ( 0.00%)
  Compiler check failed:                     0
  Could not find compiler:                   0
  Could not read or parse input file:        0
  Could not write to output file:            0
  Error hashing extra file:                  0
  Input file modified during compilation:    0
  Internal error:                            0
  Missing cache file:                        0
Successful lookups:
  Direct:                                    0 / 314 ( 0.00%)
  Preprocessed:                            301 / 314 (95.86%)
Local storage:
  Cache size (GB):                         0.1 / 0.1 (99.49%)
  Files:                                  1490
  Cleanups:                                 20
  Hits:                                    301 / 314 (95.86%)
  Misses:                                   13 / 314 ( 4.14%)
  Reads:                                   628
  Writes:                                  327
Remote storage:
  Hits:                                      0
  Misses:                                    0
  Reads:                                     0
  Writes:                                    0
  Errors:                                    0
  Timeouts:                                  0
```